### PR TITLE
Issue#28 - Changed release path to use distillery 1.0+

### PR DESCRIPTION
**Pull request by rowpsmo1859**
## Breaking Change
Needs distillery 1.0+ to work

@luckynum7 made these changes in https://github.com/edib-tool/mix-edib/issues/28

Release Notes that depict these changes
https://github.com/bitwalker/distillery/blob/master/CHANGELOG.md#100

### CODE REVIEW

**Comment by rowpsmo1859** [comment]
I guessed this will be deployed at 1.6.0

If this is wrong then the PR below needs to be changed

https://github.com/edib-tool/mix-edib/pull/29

**Comment by rowpsmo1859** [comment]
Don't deploy this yet. Found an issue.

**Comment by asaaki** [comment]
The working diff would be:

```diff
diff --git a/edib/shared.mk b/edib/shared.mk
index 1924937..694fd58 100644
--- a/edib/shared.mk
+++ b/edib/shared.mk
@@ -10,7 +10,7 @@ APP_VER        = $(shell $(APPINFO_RUNNER) version)
 
 MIX_ENV       ?= prod
 RELEASE        = releases/$(APP_VER)/$(APP_NAME).tar.gz
-RELEASE_PATH   = $(APP_DIR)/rel/$(APP_NAME)
+RELEASE_PATH   = $(APP_DIR)/_build/$(MIX_ENV)/rel/$(APP_NAME)
 RELEASE_FILE   = $(RELEASE_PATH)/$(RELEASE)
 
 STAGE_DIR      = /stage

diff --git a/tools/libdeps.exs b/tools/libdeps.exs
index 2399b70..4b93518 100755
--- a/tools/libdeps.exs
+++ b/tools/libdeps.exs
@@ -1,6 +1,8 @@
 *!/usr/bin/env elixir
 defmodule Libdeps do
-  @relpath "app/rel"
+  @current_mix_env System.get_env("MIX_ENV") || "prod"
+  @relpath "app/_build/#{@current_mix_env}"
   @lddpath_regex ~r/\/(lib|usr\/lib)[^ ]+/

   def all_files do
```

(Note: ` || "prod"` acts just as a safety net, `MIX_ENV` env var should never be unset.)

**Comment by rowpsmo1859** [comment]
@asaaki Let's use @luckynum7 PR :)

https://github.com/edib-tool/docker-edib-tool/pull/9

**Pull request closed without merging**
